version: '3'
services:
  bot:
    build: .
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      POSTGRES_DB: BoatWatcher
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  postgres_data:
  postgres_backup: