name: BoatWatcher Deploy To Production

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploying to production using SSH Script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: ~/Coding/TS/BoatWatcher/scripts/deploytoproduction
